server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.43.185
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.43.185
#阿里短信配置
leyou:
  sms:
    accessKeyId:  # 你自己的accessKeyId
    accessKeySecret:  # 你自己的AccessKeySecret
    signName: 阿里云短信测试 # 签名名称
    verifyCodeTemplate: SMS_154950909 # 模板名称